### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by fansubmaniac**
Thank's for this customizable theme !
I hope I've made no mistake, I'm not familiar with github. 
Is it possible to open Issue ? I encounter strange behavior with your theme on retropie only (the orignal theme from luciano work fine).

### CODE REVIEW

**Comment by TigraTT-Driver** [comment]
Hello, actually everything is correct. So for your first commit you did everything right :) Unfortunately I have already received a translation for french which I have only pushed in the testing branch of my repo for now. https://github.com/TigraTT-Driver/neoretro-dark/commit/f87c2a2c51835db05f5f80d370d2f36b979be5be Since there are still open points there which I don't want to transfer untested from my Android tester to the master branch, I didn't merged it yet. Can you tell me if yours or this one is better? I don't speak french and therefore can't judge the quality. Please let me know :)

Regarding your problem: I've emabled github issues now. you can open a request there https://github.com/TigraTT-Driver/neoretro-dark/issues

**Comment by fansubmaniac** [comment]
Hello, sorry I haven't seen the new translation in the test branch. Of course I can compare the translation and I'll make you my opinion.
Thank's for enabled issues, i will open a new one in the day or tomorrow.
All apologies for my poor English ...

**Comment by fansubmaniac** [comment]
Hello,

I have compared our french translations and the most parts are nearly identical. However I notice that the translation made by TigraTT-Driver is often a word to word translation. Two exemples :
- for "games_removeFavorite": TigraTT-Driver offers "RETIRER <b>FAVORIS</b>" where I offers "RETIRER DES <b>FAVORIS</b>". The "DES" is important to make a correct phrase in French. 
- for "settings_general_muteSounds": TigraTT-Driver offers "Couper sons" where I offers "Désactiver le son". Like above to be correct the phrase need "le" and we don't use the same word to translate "Mute".
To summarize TigraTT-Driver made a word to word translation where I made an adaptation translation more suitable to French Language. I'm not saying that mine is better, this is two different ways and for some parts I like the version of TigraTT-Driver.
Maybe you should ask him is opinion, a mix of the two translations could be :

global_back: "<b>RETOUR</b>", // Identical
global_select: "OK", // Identical
global_games: "JEUX", // Identical
global_noFavorites: "Aucun jeu en favoris", // I think my translation is more precise 
collection_all: "Tous", // TigraTT-Driver is more adapted to the display UI
collectionDetails_gamesAvailable: "Jeux disponibles", // Identical
games_na: "NC", // In french we use NC (Non Communiqué) or ND (Non Disponible) but not N/A
games_developedBy: "Développé par", // Identical
games_players: "JOUEURS", // Identical
games_player: "1 JOUEUR", // Identical
games_favorited: "FAVORIS", // Identical
games_withoutDescription: "sans description", // I like the translation made by TigraTT-Driver wich is shorter than mine
games_removeFavorite: "RETIRER DES <b>FAVORIS</b>", // I think mine is more french compliant with "DES"
games_addFavorite: "AJOUTER AUX <b>FAVORIS</b>", // I think mine is more french compliant with "AUX"
games_filterFavorites: "TOUS · <b>FAVORIS</b> · MULTIJOUEUR", // To make sens with the "collection_all" I propose only "TOUS" for "SHOW ALL" 
games_filterMultiplayer: "TOUS · FAVORIS · <b>MULTIJOUEUR</b>", // like above
games_filterAll: "<b>TOUS</b> · FAVORIS · MULTIJOUEUR", // like above
home_continue: "Joué récemment", // I prefer my translation wich is like "Recent game" but "Continuer" from TigraTT-Driver's translation works too.
home_favorites: "Favoris", // Identical
home_play: "Jouer", // Identical
settings_general: "Général", // TigraTT-Driver's translation is missing accent
settings_general_language: "Langue", // I think "langage" is not adapted, in most cases we use "Langue" in UI
settings_general_colorScheme: "Style de couleur", // like above "Schéma" is not adapted i think "Style" is more appropriate
settings_general_muteSounds: "Désactiver le son", // See my comment in first paragraph
settings_general_logoVariant: "Style des logos", // After thinking, none of the both translations suit me, and the word "Style" is more adapted for French.
settings_general_region: "Région", // TigraTT-Driver's translation is missing accent
settings_general_hideOSC: "Masquer les contrôles", //Like some others, for a correct phrase "les" is necessary
settings_general_OSCScheme: "Style des contrôles", // Like above with "des" and "style" in place of "Schéma" wich is not appropriate
settings_global_videoPlayback: "Lire les vidéos", // I use "Lire" instead of "Jouer" use by TigraTT-Driver. In french we "play game" but we "read video".
settings_global_videoMute: "Désactiver le son des vidéos", // I think my translation is better.
settings_collection_showAll: 'Afficher la collection "Tous"', // A mix of both translations
settings_collection_accentColor: "Accentuer la luminosité des couleurs", // A mix of both translations with correct French structure
settings_collection_accentColorNr: "Accentuer les couleurs", // A mix of both translations with correct French structure
settings_games_layout: "Mise en page des jeux", // I think my traduction "Mise en page" is more closer to the "layout" sens of word.
settings_games_gridItemsPerRow: "Grille - nombre de jeux par ligne", // I remove part of my translation to be shorter but i keep the last part more detailed
settings_games_gridItemsViewableRows: "Grille - nombre de lignes", //  Same as above
menu_settings: "réglages", // I really like the TigraTT-Driver's translation wich is shorter and fit great in the top bar. Mine was too long. 
menu_home: "accueil", // Identical
menu_collections: "collections", // Identical
menu_games:"jeux" // Identical

**Comment by TigraTT-Driver** [comment]
@fansubmaniac Thanks for checking out @HunkDeath translations. I received these as comments from him and only made the code changes, so I am the author on the commits. As I said, I almost don't understand a single word of French :smile:. Thanks for your detailed explanations of each translation and your recommendations. Since I now have to do the merging manually anyway, I will implement these suggestions and thus then close your pull request.
BTW I do not think that your English is bad :+1: :smile:

**Pull request merged**
